language: java

jdk:
  - openjdk8

#script:
    #- ./gradlew test jacocoTestReport -PexcludeTests=**/TravisExcludedTest*
    #- cp ASCIIGenome build/libs/
    #- cd src/test/java
    #- bash integration_test.sh ../../../build/libs/ASCIIGenome || true
      
after_success:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)
